security:
    # Structure améliorée pour la version 7.2
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: 'auto'

    # Activation de l'effacement des identifiants après la déconnexion
    erase_credentials: true

    # Configuration des providers
    providers:
        # La façon dont vous chargez vos utilisateurs
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Configuration du pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            # Configuration de la déconnexion
            logout:
                path: app_logout

            # Mémorisation de la session (remember me)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes

            # Vous pouvez ajouter d'autres méthodes d'authentification selon vos besoins
            # custom_authenticator: App\Security\AppAuthenticator

            # Gestion de la connexion des utilisateurs
            login_throttling:
                max_attempts: 5
                interval: '15 minutes'

    # Contrôle d'accès global
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/inventory, roles: [ROLE_SUPERVISOR, ROLE_VISITOR] }
        - { path: ^/remove, roles: [ROLE_SUPERVISOR, ROLE_USER] }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: ROLE_SUPERVISOR
        ROLE_SUPERVISOR: ROLE_USER
        ROLE_USER: ROLE_VISITOR